import Game1 from './game1.png'
import Game2 from './game2.png'
import Game3 from './game3.png'
import Game4 from './game4.png'
import Game5 from './game5.png'
import Game6 from './game6.png'
import Game7 from './game7.png'
import Game8 from './game8.png'
import Game9 from './game9.png'
import { ReactComponent as Main } from './main.svg'
export { Game1, Game2, Game3, Game4, Game5, Game6, Game7, Game8, Game9, Main }
